# pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    -   id: ruff-check
        args: [ --no-fix, --diff ]
    -   id: ruff-format 
        args: [ --check, --diff ]
