# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mypy:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade -r requirements.txt

      - uses: tsuyoshicho/action-mypy@v5.0.0
        name: Run mypy
        with:
          workdir: 'src/'

  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: macos
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade -r requirements.txt
          
      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pyinstaller
          
      - name: Run pyinstaller
        run: |
          pyinstaller RDVSpoilerLogParser.spec

      - uses: actions/upload-artifact@v4
        with:
          name: RDVSpoilerLogParser-${{ matrix.name }}
          path: ./dist/RDVSpoilerLogParser*
